# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('drive_name', models.CharField(max_length=200)),
                ('drive_date', models.DateField()),
            ],
        ),
    ]
