# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAcademicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearOfJoining', models.IntegerField()),
                ('aggregate', models.IntegerField()),
                ('senior_secondary_institute', models.CharField(max_length=30)),
                ('senior_secondary_board', models.CharField(max_length=30)),
                ('senior_secondary_percentage', models.IntegerField()),
                ('secondary_institute', models.CharField(max_length=30)),
                ('secondary_board', models.CharField(max_length=30)),
                ('secondary_percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentAdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('WISE', 'WISE'), ('ATL', 'ATL'), ('Mission R&D', 'Mission R&D'), ('Other', 'Other')], default='Other', max_length=30)),
                ('coacademicactivities', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('student_firstname', models.CharField(max_length=50)),
                ('student_lastname', models.CharField(max_length=50)),
                ('student_dob', models.DateField()),
                ('student_address', models.CharField(max_length=2000)),
                ('student_email', models.CharField(max_length=50)),
                ('student_phoneno', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='studentadditionalinfo',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentPersonalInfo'),
        ),
        migrations.AddField(
            model_name='studentacademicinfo',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentPersonalInfo'),
        ),
    ]
