# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentacademicinfo',
            name='student_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='studentadditionalinfo',
            name='student_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
