# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20170323_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=12)),
                ('student_firstname', models.CharField(max_length=50)),
                ('student_lastname', models.CharField(max_length=50)),
                ('student_address', models.CharField(max_length=2000)),
                ('student_email', models.CharField(max_length=50)),
                ('student_phoneno', models.CharField(max_length=12)),
            ],
        ),
    ]
