# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentpersonalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAcademicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearOfPass', models.IntegerField()),
                ('aggregate', models.IntegerField()),
                ('senior_secondary_institute', models.CharField(max_length=30)),
                ('senior_secondary_board', models.CharField(max_length=30)),
                ('senior_secondary_percentage', models.IntegerField()),
                ('secondary_institute', models.CharField(max_length=30)),
                ('secondary_board', models.CharField(max_length=30)),
                ('secondary_percentage', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='StudentContactDetails',
        ),
        migrations.RemoveField(
            model_name='studentpersonalinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='studentpersonalinfo',
            name='student_dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentpersonalinfo',
            name='student_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentpersonalinfo',
            name='student_phoneno',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='studentacademicinfo',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentPersonalInfo'),
        ),
    ]
