# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20170325_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentadditionalinfo',
            name='program',
        ),
        migrations.AddField(
            model_name='studentacademicinfo',
            name='program',
            field=models.CharField(choices=[('WISE', 'WISE'), ('ATL', 'ATL'), ('Mission R&D', 'Mission R&D'), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
