# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20170323_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coacademicactivities', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=2000)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentPersonalInfo')),
            ],
        ),
        migrations.RenameField(
            model_name='studentacademicinfo',
            old_name='yearOfPass',
            new_name='yearOfJoining',
        ),
    ]
